= Модель данных Ecopost
:toc:
:toc-title: Содержание

'''
== Посты наблюдений
Ecopost хранит информацию о постах наблюдений за составом воздуха. +
Посты различаются по типу и набору поддерживаемых измерений (датчиков). Скажем, концентрацию угарного газа измеряют все посты, но бензола лишь некоторые. +

.Типы постов:
* 6 постов ручного измерения (_PostManual_)
* 2 поста автоматизиторванного измерения (_PostAutomated_)
* 1 передвижной пост ручного измерения (_PostVehicle_)

.Пример сущности (entity) поста
[source,json]
----
{
    "id": "station1",
    "type": "PostManual", // <1>
    "location": {
        "type": "geo:point",
        "value": "54.966200, 73.320458", // <2>
        "metadata": {
            "area": {
                "type": "Text",
                "value": "КАО, Аэрологическая станция" // <3>
            },
            "crs": {
                "type": "Text",
                "value": "WGS84" // <4>
            }
        }
    },
    "timestamp": {
        "type": "DateTime",
        "value": "2018-05-14T08:05:02.00Z" // <5>
    },
    "carbonMonoxide": {
        "type": "Float",
        "value": 2.4,
        "metadata": {
            "dateCreated": {
                "type": "DateTime",
                "value": "2018-05-14T08:05:02.00Z" // <6>
            },
            "dateModified": {
                "type": "DateTime",
                "value": "2018-05-14T08:05:02.00Z" // <7>
            }
        }
    },
    "dust": {
        "type": "Float",
        "value": 0.2,
        "metadata": {
            "dateCreated": {
                "type": "DateTime",
                "value": "2018-05-14T08:05:02.00Z"
            },
            "dateModified": {
                "type": "DateTime",
                "value": "2018-05-14T08:05:02.00Z"
            }
        }
    }
    // ... прочие измерения
}
----
<1> Тип поста
<2> Координаты местонахождения
<3> Название округа (локализованное)
<4> Датум, в котором заданы координаты
<5> Время ввода новых данных
<6> Время создания аттрибута
<7> Время последнего изменения аттрибута. _dateCreated_ и _dateModified_ - системные метаданные, поддерживаются и обновляются атоматически, присутствуют у каждого аттрибута. В данном листинге кое-где они опущены за ненадобностью.

.Аттрибут может присутствовать или отсутствовать
[IMPORTANT]
====
Сущность содержит аттрибуты для измерений, которые данный пост поддерживает. Если пост умеет измерять бензол, то аттрибут *_benzen_* присутствует в json'е, иначе - отсутствует (_undefined_). Стоит заметить, что значением аттрибута является объект, а значение измерения находится в нем в поле *_value_*. +
====

.Специальное *_value_*
[IMPORTANT]
====
*-1* является специальным значением измерения. +
Измерение с таким значением ингорируется при расчетах, так как считается, что измерение еще не было произведено.
====

=== Начальное состояние
База данных инициализируется некоторым набором постов в начальном состоянии. Такое состояние означает, что не следует доверять значениям измерений.

* link:init_posts.adoc[Скрипт инициализации постов]

== Системные сущности

=== SystemMaximumAllowableConcentration
Системные сущности типа SystemMaximumAllowableConcentration содержат таблицы предельно допустимых значений (ПДК) для измерений.

* link:init_mac.adoc[Скрипт инициализации таблицы ПДК]

.Пример
[source,json]
----
{
    "id": "mac1",
    "type": "SystemMaximumAllowableConcentration",
    "carbonMonoxide": {
        "type": "Float",
        "value": 5
    },
    "dust": {
        "type": "Float",
        "value": 0.5
    }
    // ... прочие вещества
}
----

=== SystemProperties
*SystemProperties* существует в системе в единственном экземпляре (по крайней мере, *ecopost-ui* знает про один конкретный экземпляр по его идентификатору) и содержить данные конфигурации.

* link:init_sysprop.adoc[Скрипт инициализации SystemProperties]

.Пример
[source,json]
----
{
    "id": "systemProperties",
    "type": "SystemProperties",
    "macId": {
        "type": "Text",
        "value": "mac1" <1>
    },
    "macLevels": {
        "type": "StructuredValue",
        "value": [0.5, 0.8, 1, 1.5] <2>
    },
    "macColors": {
        "type": "StructuredValue",
        "value": ["#00FF00", "#FFFF00", "#FF8F00", "#FF8000", "#FF0000"] <3>
    },
    "decayPeriod": {
        "type": "Text",
        "value": "P2D" <4>
    }
 }
----
<1> Идентификатор используемой таблицы ПДК
<2> Уровни превышения ПДК
<3> Цвета угрозы превышения ПДК
<4> Длительность "актуальности" измерений в формате ISO8601. Другими словами, период устаревания значения.

=== Уровни и цвета превышения ПДК (_macLevels_, _macColors_)
Для отображения угрозы превышения ПДК используется следующий алгоритм:

. Пусть `x = 0.6` - текущее значение измерения вещества, для которого определен ПДК `mac = 0.5`.
. Превышение `surplus = x / mac = 1.2`.
. В массиве `macLevels = [0.5, 0.8, 1.0, 1.5]` такое превышение попадает в интервал между 2 и 3 элементом (отсчет с 0).
. Следовательно, нас интересует цвет на 3 позиции в массиве `macColors = ["#00FF00", "#FFFF00", "#FF8F00", "#FF8000", "#FF0000"]`, это `#FF8000` (отсчет с 0).
. Если в `macColors` элементов меньше необходимого, берется последний.
. Если `surplus` не превышает ни одного элемента `macLevels`, берется нулевой элемент из `macColors`.
